import dotenv from "dotenv";
dotenv.config();
import OpenAI from 'openai';


const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });


/**
* Generate a short, friendly, professional reply to the original email text
* @param {string} originalEmailText
* @returns {Promise<string>} reply text
*/
export async function generateReply(originalEmailText) {
if (!originalEmailText || originalEmailText.trim().length === 0) {
return "Thanks for your message — can you share a little more detail so I can help?";
}


try {
const systemPrompt = `You are an assistant that writes short, friendly, professional email replies. Keep it concise (3-6 sentences), confirm understanding, offer next steps, and include a warm sign-off.`;


const userPrompt = `Please write a concise professional reply to the following email content. Keep it friendly, helpful, and to the point.\n\n---\n\n${originalEmailText}\n\n---\n\nReply:`;


const response = await openai.chat.completions.create({
model: 'gpt-4o-mini',
messages: [
{ role: 'system', content: systemPrompt },
{ role: 'user', content: userPrompt },
],
max_tokens: 250,
temperature: 0.2,
});


// Response parsing depends on SDK; prefer safe access
const reply = response?.choices?.[0]?.message?.content;
if (!reply) {
throw new Error('No reply generated by OpenAI');
}


return reply.trim();
} catch (err) {
console.error('OpenAI generateReply error:', err);
// Fallback reply
return "Thanks for your message — I'll get back to you shortly.";
}
}